"""add torrent_entries table

Revision ID: 584f34ff6085
Revises: fb8a20de49ae
Create Date: 2026-03-28 10:58:22.334251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584f34ff6085'
down_revision: Union[str, Sequence[str], None] = 'fb8a20de49ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('info_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('size_display', sa.String(length=50), nullable=True),
    sa.Column('seeders', sa.Integer(), nullable=True),
    sa.Column('leechers', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('detail_url', sa.String(length=2000), nullable=True),
    sa.Column('torrent_url', sa.String(length=2000), nullable=True),
    sa.Column('uploader', sa.String(length=200), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('matched_path', sa.String(length=2000), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('torrent_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_torrent_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_torrent_entries_info_hash'), ['info_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_torrent_entries_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_torrent_entries_uploaded_at'), ['uploaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torrent_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_torrent_entries_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_torrent_entries_status'))
        batch_op.drop_index(batch_op.f('ix_torrent_entries_info_hash'))
        batch_op.drop_index(batch_op.f('ix_torrent_entries_category'))

    op.drop_table('torrent_entries')
    # ### end Alembic commands ###
